"""
Django settings for hydro_platform project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y9rhp7%pwvzldp-ruz(^st2pw+&+5#!@!()w$2&r34_z$_pjqe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_filters',  # Django REST Framework 过滤器支持
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #自己添加的三个应用users，water_structures,monitoring
    # users：用户管理（登录、权限、个人信息）
    # water_structures：	水利设施基础数据管理（静态数据）
    # monitoring：监测数据管理 + 大屏数据支持（动态数据）
    'users.apps.UsersConfig',
    'water_structures.apps.WaterStructuresConfig',
    'monitoring.apps.MonitoringConfig',

    # 注册DRF
    'rest_framework',
    'rest_framework_simplejwt',  # JWT认证支持
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hydro_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hydro_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hydro_platform',  # 数据库名
        'USER': 'root',            # MySQL 用户名
        'PASSWORD': '2004.11.01+LJH',    # MySQL 密码
        'HOST': 'localhost',       # MySQL 服务器地址
        'PORT': '3306',            # MySQL 端口
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'#设置中文

TIME_ZONE = 'Asia/Shanghai'#设置为上海时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True  # 允许所有跨域请求
CORS_ALLOW_CREDENTIALS = True  # 允许携带凭证（虽然JWT不依赖Cookie，但保留兼容性）

# DRF配置
REST_FRAMEWORK = {
    # 全局认证：使用JWT认证
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 全局权限：必须登录才能访问（登录接口除外）
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
}

# JWT配置（Token过期时间等）
from datetime import timedelta

SIMPLE_JWT = {
    # 访问Token有效期（1分钟）
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1),
    # 刷新Token有效期（7天）
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Token前缀（前端请求头格式：Authorization: Bearer <token>）
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Token刷新后是否轮换（安全性：旧Token失效）
    'ROTATE_REFRESH_TOKENS': True,
    # 轮换后是否将旧Token加入黑名单
    'BLACKLIST_AFTER_ROTATION': False,  # 简化版不启用黑名单
}