# Generated by Django 5.2.9 on 2026-01-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('water_structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_time', models.DateTimeField(verbose_name='监测时间')),
                ('inverted_plumb_up_down', models.FloatField(blank=True, null=True, verbose_name='倒垂线-上下游位移值(mm)')),
                ('inverted_plumb_left_right', models.FloatField(blank=True, null=True, verbose_name='倒垂线-左右岸位移值(mm)')),
                ('tension_wire_up_down', models.FloatField(blank=True, null=True, verbose_name='引张线-上下游位移值(mm)')),
                ('hydrostatic_leveling_settlement', models.FloatField(blank=True, null=True, verbose_name='静力水准-沉降值(mm)')),
                ('water_level_upstream', models.FloatField(blank=True, null=True, verbose_name='上游水位值(m)')),
                ('water_level_downstream', models.FloatField(blank=True, null=True, verbose_name='下游水位值(m)')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '预警'), ('alarm', '告警')], default='normal', max_length=10, verbose_name='预警状态')),
                ('monitor_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='监测人员')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统录入时间')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_records', to='water_structures.point', verbose_name='关联监测点')),
            ],
            options={
                'verbose_name': '动态监测数据',
                'verbose_name_plural': '动态监测数据',
                'ordering': ['-monitor_time'],
                'unique_together': {('point', 'monitor_time')},
            },
        ),
    ]
