# Generated by Django 5.2.9 on 2026-01-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('inverted_plumb_up_down', '倒垂线-上下游位移监测'), ('inverted_plumb_left_right', '倒垂线-左右岸位移监测'), ('tension_wire_up_down', '引张线-上下游位移监测'), ('hydrostatic_leveling', '静力水准-沉降监测'), ('water_level_upstream', '水位传感器-上游水位监测'), ('water_level_downstream', '水位传感器-下游水位监测')], max_length=50, verbose_name='设备类型（仪器+监测指标）')),
                ('install_position', models.CharField(max_length=200, verbose_name='设备安装位置（相对大坝）')),
                ('install_time', models.DateField(blank=True, null=True, verbose_name='设备安装时间')),
                ('device_status', models.CharField(choices=[('running', '正常运行'), ('stopped', '停用'), ('faulty', '设备故障')], default='running', max_length=20, verbose_name='设备运行状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统录入时间')),
            ],
            options={
                'verbose_name': '监测设备',
                'verbose_name_plural': '监测设备',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='大坝名称')),
                ('cesium_center_x', models.FloatField(verbose_name='Cesium大坝中心点X（世界坐标）')),
                ('cesium_center_y', models.FloatField(verbose_name='Cesium大坝中心点Y（世界坐标）')),
                ('cesium_center_z', models.FloatField(verbose_name='Cesium大坝中心点Z（世界坐标/高程）')),
                ('cesium_heading', models.FloatField(default=0.0, verbose_name='Cesium大坝模型航向角')),
                ('cesium_pitch', models.FloatField(default=0.0, verbose_name='Cesium大坝模型俯仰角')),
                ('cesium_roll', models.FloatField(default=0.0, verbose_name='Cesium大坝模型翻滚角')),
                ('cesium_scale', models.FloatField(default=1.0, verbose_name='Cesium大坝模型缩放比例')),
                ('cesium_model_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cesium大坝3D模型文件路径')),
                ('level', models.CharField(choices=[('1级', '1级大坝'), ('2级', '2级大坝'), ('3级', '3级大坝')], default='2级', max_length=20, verbose_name='大坝等级')),
                ('completion_time', models.DateField(blank=True, null=True, verbose_name='大坝建成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统录入时间')),
            ],
            options={
                'verbose_name': '大坝信息',
                'verbose_name_plural': '大坝信息',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_code', models.CharField(max_length=50, unique=True, verbose_name='测点编号')),
                ('relative_x', models.FloatField(verbose_name='相对大坝X坐标（局部）')),
                ('relative_y', models.FloatField(verbose_name='相对大坝Y坐标（局部）')),
                ('relative_z', models.FloatField(verbose_name='相对大坝Z坐标（局部/高程）')),
                ('displacement_upper', models.FloatField(blank=True, null=True, verbose_name='位移预警上限(mm)')),
                ('displacement_lower', models.FloatField(blank=True, null=True, verbose_name='位移预警下限(mm)')),
                ('settlement_upper', models.FloatField(blank=True, null=True, verbose_name='沉降预警上限(mm)')),
                ('settlement_lower', models.FloatField(blank=True, null=True, verbose_name='沉降预警下限(mm)')),
                ('water_level_upper', models.FloatField(blank=True, null=True, verbose_name='水位预警上限(m)')),
                ('water_level_lower', models.FloatField(blank=True, null=True, verbose_name='水位预警下限(m)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统录入时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bind_point', to='water_structures.monitoringdevice', verbose_name='绑定监测设备')),
            ],
            options={
                'verbose_name': '监测点',
                'verbose_name_plural': '监测点',
                'ordering': ['point_code'],
            },
        ),
        migrations.AddField(
            model_name='monitoringdevice',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_devices', to='water_structures.structure', verbose_name='所属大坝'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringdevice',
            unique_together={('structure', 'install_position', 'device_type')},
        ),
    ]
