# Generated by Django 5.2.9 on 2026-01-05 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '系统管理员（可操作所有数据）'), ('monitor', '监测员（可录入/查看数据）'), ('viewer', '数据查看者（仅可查看数据）')], default='viewer', max_length=10, verbose_name='用户角色')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属部门')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='账号创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联系统用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
